### PR TITLE
fix regular expression

### PR DESCRIPTION
**Pull request by dfreudenberger**
fyi @rebuy-de/prp-nginx-exporter

### CODE REVIEW

**Comment by paskal** [comment]
I've tried master version with nginx log format from readme and from file itself, both didn't work.
When it will be ready, readme could be updated with new release version, new log format (if necessary) and notes on migration from v1.

**Comment by dfreudenberger** [comment]
```
 log_format mtail '$server_name $remote_addr - $remote_user [$time_local] '
                  '"$request" $status $bytes_sent $request_time'
                  '"$http_referer" "$http_user_agent" "$content_type" "$upstream_cache_status"';
```

didn't work for you? That would be strange because that's what we have running in production. Readme should be updated, will take care of it as soon as I've heard something back from you.

**Comment by paskal** [comment]
I'll check it by the end of the weekend and will be back to you with the answer. I've tried readme version with master image, and it didn't work, and I've tried version [from there](https://github.com/rebuy-de/nginx-exporter/blob/master/assets/nginx.mtail), it didn't work either - only readme version + v1.0.0 image combination worked.

**Comment by paskal** [comment]
@dfreudenberger, I've checked: it doesn't work in my case. On http://container:3093/metrics I see only following:
```bash
/ # curl http://localhost:3093/metrics
# TYPE nginx_requests_total counter
# TYPE nginx_request_duration_milliseconds_sum counter
# TYPE nginx_response_size_bytes_sum counter
```
mtail format:
```nginx    log_format mtail '$server_name $remote_addr - $remote_user [$time_local] '
                     '"$request" $status $bytes_sent $request_time'
                     '"$http_referer" "$http_user_agent" "$content_type" "$upstream_cache_status"';
```
Image:
```yaml
image: quay.io/rebuy/nginx-exporter:master
```
Log line example:
```bash
/ # tail -1 /var/log/nginx/mtail/access.log
grafana.some.some.net 10.36.0.48 - - [26/Nov/2018:11:15:28 +0000] "GET /api/annotations?dashboardId=1&from=1543220127380&to=1543230927380 HTTP/1.0" 200 199 0.461"https://grafana.some.some.net/d/a6e7d1362e1ddbb79db21d5bb40d7137/k8s-use-method-cluster?refresh=10s&orgId=1&from=now-3h&to=now&kiosk" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" "-" "-"
```
Could you by chance have different container variables, maybe some different ENV than one specified in README.md?

**Comment by bjoernhaeuser** [comment]
@paskal today we pushed a new tag to quay (`v1.1.0-RC1`). There it works with the mentioned log format.

**Comment by bjoernhaeuser** [comment]
I just also updated the README, I think your mtail format is wrong :)

**Comment by paskal** [comment]
I wrote which one I've used, it's the same you posted there. Also, in readme there is still an old version:
```quay.io/rebuy/nginx-exporter:v1.0.0```

**Comment by bjoernhaeuser** [comment]
@paskal 

There is a space missing after `request_time`, you can see this in your log line. 

Right now:

```
0.461"https://grafana.some.some.ne
```

Required:
```
0.461 "https://grafana.some.some.ne
```

The release still shows the 1.0.0, because we tagged 1.1.0-RC1. 

If this does not work, please paste your complete nginx config, or as much you can. Thanks!

**Comment by paskal** [comment]
I'll test shortly. https://github.com/rebuy-de/nginx-exporter/blob/master/assets/nginx.mtail#L10 misses the space you mention, and https://github.com/rebuy-de/nginx-exporter/pull/8#issuecomment-440981876 as well misses it.
Format from current readme works, problem solved.

**Comment by bjoernhaeuser** [comment]
Good catch! Will fix.

**Comment by bjoernhaeuser** [comment]
@paskal I fixed the wrong format in the `nginx.mtail`. 

Thanks for conforming that its works for you now!

**Pull request merged**
