### PR TITLE
use exporter-merger

### PR DESCRIPTION
**Pull request by svenwltr**
> https://github.com/rebuy-de/exporter-merger

### CODE REVIEW

**Comment by svenwltr** [comment]
@rebuy-de/it-platform Please review.

**Review by bjoernhaeuser — APPROVED** [review]

**Comment by bjoernhaeuser** [comment]
no `.travis.yml`?

**Comment by svenwltr** [comment]
@bjoernhaeuser It currently only produces a Docker image in Quay.io. Should we also add a binary release?

**Comment by bjoernhaeuser** [comment]
Yeah, i would say so

**Comment by svenwltr** [comment]
Ahh ... we don't have binaries in this project.

**Comment by svenwltr** [comment]
bump

**Review by bjoernhaeuser — APPROVED** [review]

**Review by stephanlindauer — APPROVED** [review]

**Pull request merged**
